# **# Actividad N°3 de Programación II**

## # Ejercicio de Datos Complejos en Python

+ Crear una lista de nombre de ciudades

In [150]:
ciudades=["Posadas","Buenos Aires","Ushuaia","Bariloche","Federación" ]
print (ciudades)

['Posadas', 'Buenos Aires', 'Ushuaia', 'Bariloche', 'Federación']

+ Crear un diccionario con información de empleados (nombre, cargo, salario)

+ (Version Diccionario de diccionario)

In [151]:
empleados ={"1":{"Nombre":"Sandra","Cargo":"Data Engineer","Salario":3500},
            "2":{"Nombre":"Ivan","Cargo":"Data Scientist","Salario":2500},
            "3":{"Nombre":"Santiago","Cargo":"Data Analyst","Salario":1500}}
print (empleados)

{'1': {'Nombre': 'Sandra', 'Cargo': 'Data Engineer', 'Salario': 3500}, '2': {'Nombre': 'Ivan', 'Cargo': 'Data Scientist', 'Salario': 2500}, '3': {'Nombre': 'Santiago', 'Cargo': 'Data Analyst', 'Salario': 1500}}

+ Mostrar cómo acceder a un elemento específico en una lista y en un diccionario

In [152]:
posadas=ciudades[0]
print ("Ciudad 1: ",posadas)
bs_as=ciudades[1]
print ("Ciudad 2: ",bs_as)

Ciudad 1:  Posadas
Ciudad 2:  Buenos Aires

In [153]:
print ("Ciudad 3:",ciudades[2])
print ("Ciudad 4:",ciudades[3])
print ("Ciudad 5:",ciudades[4])

Ciudad 3: Ushuaia
Ciudad 4: Bariloche
Ciudad 5: Federación

In [154]:
print (empleados["1"])
print (empleados["2"])
print (empleados["3"])

{'Nombre': 'Sandra', 'Cargo': 'Data Engineer', 'Salario': 3500}
{'Nombre': 'Ivan', 'Cargo': 'Data Scientist', 'Salario': 2500}
{'Nombre': 'Santiago', 'Cargo': 'Data Analyst', 'Salario': 1500}

In [155]:
empleados_2={"Sandra":["Data Engineer",3500],
             "Ivan":["Data Scientist",2500],
             "Santiago":["Data Analyst",1500]}

+ (Version Diccionario de Lista)

In [156]:
print ("Cargo Sandra:",empleados_2["Sandra"][0]," - ","Sueldo:",empleados_2["Sandra"][1],"U$S")
print ("Cargo Ivan:",empleados_2["Ivan"][0]," - ","Sueldo:",empleados_2["Ivan"][1],"U$S")
print ("Cargo Santiago:",empleados_2["Santiago"][0]," - ","Sueldo:",empleados_2["Santiago"][1],"U$S")

Cargo Sandra: Data Engineer  -  Sueldo: 3500 U$S
Cargo Ivan: Data Scientist  -  Sueldo: 2500 U$S
Cargo Santiago: Data Analyst  -  Sueldo: 1500 U$S

+ Crea una lista inicial de números enteros.
+ Utiliza el método .append() para agregar un número al final de la lista. 
+ Utiliza el método .extend() para agregar múltiples elementos a la lista. 
+ Utiliza el método .insert() para insertar un número en una posición específica de la lista. 
+ Muestra cómo utilizar el método .sort() para ordenar la lista de números de forma ascendente.

In [157]:
numeros =[10,20,30,40,55]
numeros.append(100)
numeros2=[5,15,35]
numeros.extend(numeros2)

In [158]:
print (numeros)

[10, 20, 30, 40, 55, 100, 5, 15, 35]

In [159]:
numeros.insert(0,1)

In [160]:
print(numeros)

[1, 10, 20, 30, 40, 55, 100, 5, 15, 35]

In [161]:
numeros.sort()

In [162]:
print (numeros)

[1, 5, 10, 15, 20, 30, 35, 40, 55, 100]

+ Crea un diccionario con información de productos (nombre del producto, precio, cantidad en stock). 
+ Utiliza el método .keys() para obtener una lista de las llaves (nombres de productos) en el diccionario. 
+ Utiliza el método .values() para obtener una lista de los valores (precios y cantidades) en el diccionario.
+ Utiliza el método .items() para obtener una lista de tuplas con pares clave-valor del diccionario. 
+ Muestra cómo utilizar el método .get() para obtener el precio de un producto específico del diccionario.

In [163]:
productos={"Vino Tinto":{"Precio":5000,"Stock":150},
           "Vino Blanco":{"Precio":3500,"Stock":100},
           "Gaseosas":{"Precio":2500,"Stock":250},
           "Jugos":{"Precio":2000,"Stock":200},
           "Agua mineral":{"Precio":1500,"Stock":300}}

In [164]:
productos.keys()

dict_keys(['Vino Tinto', 'Vino Blanco', 'Gaseosas', 'Jugos', 'Agua mineral'])

In [165]:
productos.values()

dict_values([{'Precio': 5000, 'Stock': 150}, {'Precio': 3500, 'Stock': 100}, {'Precio': 2500, 'Stock': 250}, {'Precio': 2000, 'Stock': 200}, {'Precio': 1500, 'Stock': 300}])

In [166]:
productos.items()

dict_items([('Vino Tinto', {'Precio': 5000, 'Stock': 150}), ('Vino Blanco', {'Precio': 3500, 'Stock': 100}), ('Gaseosas', {'Precio': 2500, 'Stock': 250}), ('Jugos', {'Precio': 2000, 'Stock': 200}), ('Agua mineral', {'Precio': 1500, 'Stock': 300})])

In [167]:
items_productos = productos.items()
print("Items de productos:", items_productos)

Items de productos: dict_items([('Vino Tinto', {'Precio': 5000, 'Stock': 150}), ('Vino Blanco', {'Precio': 3500, 'Stock': 100}), ('Gaseosas', {'Precio': 2500, 'Stock': 250}), ('Jugos', {'Precio': 2000, 'Stock': 200}), ('Agua mineral', {'Precio': 1500, 'Stock': 300})])

In [168]:
precio_vinotinto = productos.get("Vino Tinto").get("Precio")
print("Precio del Vino Tinto: ", precio_vinotinto,"Pesos")

Precio del Vino Tinto:  5000 Pesos

In [169]:
precio_vinobco = productos.get("Vino Blanco").get("Precio")
print("Precio del Vino Blanco: ", precio_vinobco,"Pesos")

Precio del Vino Blanco:  3500 Pesos

In [170]:
precio_gaseosas = productos.get("Gaseosas").get("Precio")
print("Precio de las Gaseosas: ", precio_gaseosas,"Pesos")

Precio de las Gaseosas:  2500 Pesos

In [171]:
precio_jugos = productos.get("Jugos").get("Precio")
print("Precio de los Jugos: ", precio_jugos,"Pesos")

Precio de los Jugos:  2000 Pesos

In [172]:
precio_agua = productos.get("Agua mineral").get("Precio")
print("Precio del Agua Mineral: ", precio_agua,"Pesos")

Precio del Agua Mineral:  1500 Pesos

+ Cree una lista de diccionarios que representen información de libros (título, autor, año de publicación).
+ Cree un diccionario que contenga listas como valores (por ejemplo, un diccionario de estudiantes y sus materias). 
+ Mostrar cómo modificar un valor en una lista dentro de un diccionario y viceversa.

In [186]:
libros= {"Libro 1": ["El poder del ahora","Autor:","Eckhart Tolle","Año_publicación": 1997],
        "Libro 2":["El resplandor", "Autor: ","Stephen King", "Año_publicación": 1977],
        "Libro 3":["El principito", "Autor: ","Antoine de Saint-Exupéry", "Año_publicación": 1943]}

SyntaxError: invalid syntax (2270474298.py, line 1)

In [ ]:
print (libros)

[{'título': 'El alquimista', 'autor': 'Paulo Coelho', 'año_publicación': 1988}, {'título': 'Cien años de soledad', 'autor': 'Gabriel García Márquez', 'año_publicación': 1967}, {'título': 'El principito', 'autor': 'Antoine de Saint-Exupéry', 'año_publicación': 1943}]