# **# Actividad N°3 de Programación II**

## # Ejercicio de Datos Complejos en Python

+ Crear una lista de nombre de ciudades

In [2]:
ciudades=["Posadas","Buenos Aires","Ushuaia","Bariloche","Federación" ]
print (ciudades)

['Posadas', 'Buenos Aires', 'Ushuaia', 'Bariloche', 'Federación']

+ Crear un diccionario con información de empleados (nombre, cargo, salario)

+ (Version Diccionario de diccionario)

In [33]:
empleados ={"1":{"Nombre":"Sandra","Cargo":"Data Engineer","Salario":3500},
            "2":{"Nombre":"Ivan","Cargo":"Data Scientist","Salario":2500},
            "3":{"Nombre":"Santiago","Cargo":"Data Analyst","Salario":1500}}
print (empleados)

{'1': {'Nombre': 'Sandra', 'Cargo': 'Data Engineer', 'Salario': 3500}, '2': {'Nombre': 'Ivan', 'Cargo': 'Data Scientist', 'Salario': 2500}, '3': {'Nombre': 'Santiago', 'Cargo': 'Data Analyst', 'Salario': 1500}}

+ Mostrar cómo acceder a un elemento específico en una lista y en un diccionario

In [32]:
posadas=ciudades[0]
print ("Ciudad 1: ",posadas)
bs_as=ciudades[1]
print ("Ciudad 2: ",bs_as)

Ciudad 1:  Posadas
Ciudad 2:  Buenos Aires

In [28]:
print ("Ciudad 3:",ciudades[2])
print ("Ciudad 4:",ciudades[3])
print ("Ciudad 5:",ciudades[4])

Ciudad 3: Ushuaia
Ciudad 4: Bariloche
Ciudad 5: Federación

In [30]:
print (empleados["1"])
print (empleados["2"])
print (empleados["3"])

{'Nombre': 'Sandra', 'Cargo': 'Data Engineer', 'Salario': 3500}
{'Nombre': 'Ivan', 'Cargo': 'Data Scientist', 'Salario': 2500}
{'Nombre': 'Santiago', 'Cargo': 'Data Analyst', 'Salario': 1500}

In [34]:
empleados_2={"Sandra":["Data Engineer",3500],
             "Ivan":["Data Scientist",2500],
             "Santiago":["Data Analyst",1500]}

+ (Version Diccionario de Lista)

In [48]:
print ("Cargo Sandra:",empleados_2["Sandra"][0]," - ","Sueldo:",empleados_2["Sandra"][1],"U$S")
print ("Cargo Ivan:",empleados_2["Ivan"][0]," - ","Sueldo:",empleados_2["Ivan"][1],"U$S")
print ("Cargo Santiago:",empleados_2["Santiago"][0]," - ","Sueldo:",empleados_2["Santiago"][1],"U$S")

Cargo Sandra: Data Engineer  -  Sueldo: 3500 U$S
Cargo Ivan: Data Scientist  -  Sueldo: 2500 U$S
Cargo Santiago: Data Analyst  -  Sueldo: 1500 U$S

+ Crea una lista inicial de números enteros.
+ Utiliza el método .append() para agregar un número al final de la lista. 
+ Utiliza el método .extend() para agregar múltiples elementos a la lista. 
+ Utiliza el método .insert() para insertar un número en una posición específica de la lista. 
+ Muestra cómo utilizar el método .sort() para ordenar la lista de números de forma ascendente.

In [72]:
numeros =[10,20,30,40,55]
numeros.append(100)
numeros2=[5,15,35]
numeros.extend(numeros2)

In [73]:
print (numeros)

[10, 20, 30, 40, 55, 100, 5, 15, 35]

In [74]:
numeros.insert(0,1)

In [75]:
print(numeros)

[1, 10, 20, 30, 40, 55, 100, 5, 15, 35]

In [76]:
numeros.sort()

In [77]:
print (numeros)

[1, 5, 10, 15, 20, 30, 35, 40, 55, 100]